[package]
name = "osas"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "osas"
crate-type = ["cdylib"]

[dependencies]
actix = "0.13.5"
pyo3 = "0.23.1"
rodio = "0.20.1"
